---
- name: Install NGINX
  yum: name=nginx state=present

- name: Copy NGINX base configuration file
  template: src=nginx.conf dest=/etc/nginx/nginx.conf
  notify: restart nginx

- name: Copy NGINX default configuration file
  template: src=default.conf dest=/etc/nginx/conf.d/default.conf
  notify: restart nginx

- name: Create firewall rule for NGINX
  firewalld: service=http permanent=true state=enabled immediate=yes
  ignore_errors: yes

- name: Enable and start NGINX
  service: name=nginx state=started enabled=yes