---
- name: Copy the NGINX repository definition
  copy: src=nginx.repo dest=/etc/yum.repos.d/

- name: Copy the EPEL repository definition
  copy: src=epel.repo dest=/etc/yum.repos.d/

- name: Create the GPG key for NGINX
  copy: src=RPM-GPG-KEY-NGINX dest=/etc/pki/rpm-gpg

- name: Create the GPG key for EPEL
  copy: src=RPM-GPG-KEY-EPEL-7 dest=/etc/pki/rpm-gpg

- name: Install firewalld
  yum: name=firewalld state=present

- name: Enable and start firewalld
  service: name=firewalld state=started enabled=yes

- name: Install vim
  yum: name=vim state=present

- name: Install htop
  yum: name=htop state=present

- name: Secure SSHD
  template: src=sshd_config dest=/etc/ssh/sshd_config
  notify: restart sshd

- name: Make shell beautiful
  lineinfile:
    dest: /root/.bashrc
    owner: root
    line: 'export PS1="\[\033[38;5;33m\][\[$(tput sgr0)\]\[\033[38;5;4m\]\A\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]\[\033[38;5;39m\]\u\[$(tput sgr0)\]\[\033[38;5;42m\]@\[$(tput sgr0)\]\[\033[38;5;41m\]\h\[$(tput sgr0)\]\[\033[38;5;14m\]:\[$(tput sgr0)\]\[\033[38;5;61m\]\W\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]\[\033[38;5;151m\]\\$\[$(tput sgr0)\]\[\033[38;5;33m\]]\[$(tput sgr0)\]\[\033[38;5;15m\] \[$(tput sgr0)\]"'
