---
- name: common packages are installed
  apt:
    pkg:
      - "sudo"
      - "curl"
      - "locales"
      - "git"
      - "whois"
      - "wget"
      - "strace"
      - "sysstat"
      - "iotop"
      - "iperf"
      - "lsof"
      - "dnsutils"
      - "ngrep"
      - "htop"
      - "netcat"
      - "multitail"
      - "tmux"
      - "tree"
      - "ncdu"
      - "net-tools"
      - "procps"
      - "vim"
      - "jq"
      - "rsyslog"
      - "logrotate"
      - "unattended-upgrades"
      - "build-essential"
      - "zlib1g-dev"
      - "zlib1g"
      - "libcurl4-openssl-dev"
      - "fish"
    state: present
    update_cache: true

- name: root user uses fish shell
  user:
    name: root
    shell: "/usr/bin/fish"

- name: basic groups exist
  group:
    state: present
    name: "{{ item }}"
  with_items:
    - "admin"
    - "docker"

- name: application user exists
  user:
    append: yes
    generate_ssh_key: yes
    groups:
      - docker
      - admin
    name: "{{ username | default('web') }}"
    shell: "/usr/bin/fish"
    password: "{{ password | password_hash('sha512')}}"
    update_password: on_create
  register: user

- name: force user to change password
  shell: "chage -d 0 {{ user.name }}"
  when: user.changed

- include: ssh.yml
- include: ufw.yml